pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: API_DIRECTORY
    value: 'DDDBrisbane.API.Product'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - DDDBrisbane.API.Product
    - Core
    
pr:
  branches:
    include:
    - main
  paths:
    include:
      - DDDBrisbane.API.Product
      - Core
      
extends:
  template: ../Deployment/azure-pipelines.yml
