stages:
- stage: Build_Test_Deploy
  displayName: 'Build, Test, and Deploy'
  jobs:
  - job: Build_Test_Deploy
    displayName: Build Test, and Deploy
    steps:
    - script: python3 ./main.py
      workingDirectory: $(API_DIRECTORY)

