stages:
- stage: Build_Test_Deploy
  displayName: 'Build, Test, and Deploy'
  jobs:
  - job: TestCore
    displayName: Build Test, and Deploy
    steps:
    - script: ./main
      workingDirectory: $(API_DIRECTORY)

